#pragma once

#define OLED_TIMEOUT 15000
#define OLED_BRIGHTNESS 120

#define MASTER_LEFT

#define USE_SERIAL_PD2

#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 250

#define TIME_CAPS_ACTIVE 10000
#define TIME_TAP_HOLD 250